### PR TITLE
**bug** Primary Email field does not exist

### PR DESCRIPTION
**Pull request by ljrodriguez1**
When trying to create a user with the primary email field the API returns the next error ` {"success":false,"error":"Invalid field(s) in the payload: primary_email","error_info":"Please check developers.pipedrive.com for more information about Pipedrive API.","data":null,"additional_data":null}`

Instead, we need to use the email field. I think we should remove this from the documentation because it cause confusion.

### CODE REVIEW

**Comment by pipedrive-bot-eventsink** [comment]
### Main branch dependencies
[snyk vulnerabilities](https://app.snyk.io/org/gravity-byw/project/012bf507-7160-48ba-8614-93238df62ea1)

**Comment by siirimangus** [comment]
Hey!

POST endpoint is not using the `NewUser.md` model but `AddUserRequest.md` instead.

In the `addUser` function it is stated:
https://github.com/pipedrive/client-nodejs/blob/bf35470a72334de90e889b534b34d4b360a43c85/src/api/UsersApi.js#L104

which leads to `AddUserRequest.md` model instead:
https://github.com/pipedrive/client-nodejs/blob/master/docs/AddUserRequest.md

So yes, the `primary_email` field cannot be set during POST request, but should be available in `GET /v1/persons` and `GET /v1/persons/{id}` endpoints.

Does it seem correct?

**Comment by ljrodriguez1** [comment]
Then in the addPerson Docs:
https://github.com/pipedrive/client-nodejs/blob/master/docs/PersonsApi.md#addPerson

the parameters should be `AddUserRequest.md`

I am following that documentation and that is where I was misleading.

**Comment by ljrodriguez1** [comment]
On another note I find weird that for addUser we use `AddUserRequest.md` because I am using the client and the parameters that I passed are the ones indicated on `NewUser.md` without the `primaryEmail` and it worked correctly, I was capable of passing the `phone` attribute for example

**Comment by siirimangus** [comment]
> Then in the addPerson Docs: https://github.com/pipedrive/client-nodejs/blob/master/docs/PersonsApi.md#addPerson
> 
> the parameters should be `AddUserRequest.md`
> 
> I am following that documentation and that is where I was misleading.

Yes, that is definitely misleading, thanks for pointing this out. As the docs are autogenerated, we won't merge this PR, but try to fix this at the root level. I'll keep you updated.

**Comment by siirimangus** [comment]
> On another note I find weird that for addUser we use `AddUserRequest.md` because I am using the client and the parameters that I passed are the ones indicated on `NewUser.md` without the `primaryEmail` and it worked correctly, I was capable of passing the `phone` attribute for example

Actually, this is a common practice (not to say a must) when describing the API following the openapi specification - if there's a need for a model that is slightly different (in this case `primaryEmail` should not exist), then a new model needs to be defined.
I'll communicate this to our API team whether those "hidden" optional parameters should also be listed in our docs: https://developers.pipedrive.com/docs/api/v1/Users#addUser

**Comment by siirimangus** [comment]
> Then in the addPerson Docs: https://github.com/pipedrive/client-nodejs/blob/master/docs/PersonsApi.md#addPerson
> 
> the parameters should be `AddUserRequest.md`
> 
> I am following that documentation and that is where I was misleading.

Just to make it clear - are you trying to `addUser` or `addPerson`? They are two different API-s.

The `addUser` function belongs to the [`UsersApi`](https://github.com/pipedrive/client-nodejs/blob/master/docs/UsersApi.md) and in there the [`addUser`](https://github.com/pipedrive/client-nodejs/blob/master/docs/UsersApi.md#addUser) parameters are correct (`AddUserRequest.md`). And there is no model named `NewUser` available.

The `addPerson` function belongs to the [`PersonsApi`](https://github.com/pipedrive/client-nodejs/blob/master/docs/PersonsApi.md) and in there the `addPerson` parameters use a `NewPerson` model.

**Comment by siirimangus** [comment]
> On another note I find weird that for addUser we use `AddUserRequest.md` because I am using the client and the parameters that I passed are the ones indicated on `NewUser.md` without the `primaryEmail` and it worked correctly, I was capable of passing the `phone` attribute for example

This is a very common practice actually (not to say a must) that whenever a model is needed that differs in some fields from the other model, a new one is created. It's true, I see that you can pass some parameters that are not listed (`phone`), but it doesn't have any effect, the phone number will not be set.

**Comment by siirimangus** [comment]
I'm closing this PR as it seems there was some confusion caused by following the incorrect docs.
If there's still anything suspicious or seems off, feel free to open a PR or raise an issue.

**Comment by ljrodriguez1** [comment]
Hi Sorry for the late response, I was using the `addPerson` API, where as you said we need to pass the `NewPerson` params, still the problem persist, because `NewPerson` shows we can pass a `primaryEmail` field, but when passing it, it throws the error written above

**Pull request closed without merging**
