### PR TITLE
Set fixed version for inflection.js

### LINKED ISSUE #89: ENOENT: no such file or directory, open '//../package.json'
Not sure if this is a problem for others, but I came accross this when bundling the client using [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack).

Basically the client expects a `package.json` in its root directory from which it fetches the version. 

https://github.com/pipedrive/client-nodejs/blob/09d1a238b63f4d929a8c7c9a239082161d014597/lib/inflection.js#L564-L566

The script is making some assumptions about it's runtime environment that may not be guaranteed. 

Any chance of removing this?

### PR DESCRIPTION
**Pull request by JohannesHome**
fixes #89

### CODE REVIEW

**Comment by DenisButCheR** [comment]
Why you made a lot of changes for code style ????

**Comment by JohannesHome** [comment]
@DenisButCheR habit, it's mainly whitespaces. Look here to see the diff without whitespaces: https://github.com/pipedrive/client-nodejs/pull/90/files?w=1

It also doesn't effect git blame if that is what you are worried about ;)

You want me to remove it?

**Comment by DenisButCheR** [comment]
Yes, please make only useful changes in PR, no whitespace fixes and other cosmetics.

**Comment by JohannesHome** [comment]
I adjusted the PR. You should think about adding contribution guidelines, it is very frustrating to have to have to change things like whitespaces ;)

**Comment by perry-mitchell** [comment]
Any chance on getting this merged and released soon? We're a client and this is affecting us downstream. It'd be great to get this out asap! Thanks.

**Comment by sabarasaba** [comment]
I've been blocked on this long enough so I created a fork and applied the patch myself and we're now using that https://www.npmjs.com/package/pipedrive-fix. Ill whack it after this is merged, if it ever happens.

**Comment by RuTsEST** [comment]
This PR fixes the issue #99

**Pull request closed without merging**
