### PR TITLE
GRAL-2883: bump superagent version

### PR DESCRIPTION
**Pull request by IgnorancePulls**
https://pipedrive.atlassian.net/jira/software/c/projects/GRAL/boards/344?modal=detail&selectedIssue=GRAL-2883

bump superagent version

### CODE REVIEW

**Comment by pipedrive-bot-eventsink** [comment]
### Main branch dependencies
[snyk vulnerabilities](https://app.snyk.io/org/gravity-byw/project/012bf507-7160-48ba-8614-93238df62ea1)

**Comment by siirimangus** [comment]
CHANGELOG file also needs an update about this change, check this PR for an example: https://github.com/pipedrive/client-nodejs/pull/333/files

**Review by siirimangus — APPROVED** [review]
🚀

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ✅


Commit [`c337306`](https://github.com/pipedrive/client-nodejs/commit/c3373063a566c7dc951c5b8c422842292dc78a63/)  Job [`27851`](https://jenkins.pipedrive.tools/job/neodora/27851/)

**Pull request merged**
