### PR TITLE
GRAL-3919 Changed node version in .nvmrc and fixed vulnerable dependencies

### PR DESCRIPTION
**Pull request by SpaceOven**
## Changes
This PR applies some maintenance in node version and dependencies.
- Bumped node version to 18 in .nvmrc
- Fixed vulnerable dependencies

### CODE REVIEW

**Comment by pipedrive-bot-eventsink** [comment]
### Main branch dependencies
[snyk vulnerabilities](https://app.snyk.io/org/gravity-byw/project/012bf507-7160-48ba-8614-93238df62ea1)

**Review by siirimangus — APPROVED** [review]
LGTM 🚀

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Missing Snyk Branch Protection for repository</strong></summary>
<br/>

**Message:** Branch protection must be configured on every GitHub repository. Snyk checks must be in the list of required checks of the branch protection rule

<table>
<thead>
	<tr>
			<th>Snyk checks status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/settings/branches">Required checks are missing: code/snyk</a></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/snykBranchProtection)
<br/>
</details>

<details><summary><strong> ⚠ Missing or invalid timeout in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow timeout-minutes must be set with a value less or equal to 60 for every job that is not using a reusable workflow

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual timeout</th>
			<th>Expected</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>Not found</td>
				<td><= 60</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowTimeout)
<br/>
</details>


Commit [`3da2e9d`](https://github.com/pipedrive/client-nodejs/commit/3da2e9d47cb3dfff35e54bc42e3d7f2b2b3530d6/)  Job [`285124`](https://jenkins.pipedrive.tools/job/neodora/285124/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Missing or invalid timeout in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow timeout-minutes must be set with a value less or equal to 60 for every job that is not using a reusable workflow

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual timeout</th>
			<th>Expected</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ed75b2d7fddda622df31905b8d553a4d227ecd0d/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>Not found</td>
				<td><= 60</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowTimeout)
<br/>
</details>

<details><summary><strong> ⚠ Missing Snyk Branch Protection for repository</strong></summary>
<br/>

**Message:** Branch protection must be configured on every GitHub repository. Snyk checks must be in the list of required checks of the branch protection rule

<table>
<thead>
	<tr>
			<th>Snyk checks status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/settings/branches">Required checks are missing: code/snyk</a></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/snykBranchProtection)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ed75b2d7fddda622df31905b8d553a4d227ecd0d/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ed75b2d7fddda622df31905b8d553a4d227ecd0d/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ed75b2d7fddda622df31905b8d553a4d227ecd0d/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ed75b2d7fddda622df31905b8d553a4d227ecd0d/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>


Commit [`ed75b2d`](https://github.com/pipedrive/client-nodejs/commit/ed75b2d7fddda622df31905b8d553a4d227ecd0d/)  Job [`285347`](https://jenkins.pipedrive.tools/job/neodora/285347/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Missing Snyk Branch Protection for repository</strong></summary>
<br/>

**Message:** Branch protection must be configured on every GitHub repository. Snyk checks must be in the list of required checks of the branch protection rule

<table>
<thead>
	<tr>
			<th>Snyk checks status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/settings/branches">Required checks are missing: code/snyk</a></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/snykBranchProtection)
<br/>
</details>

<details><summary><strong> ⚠ Missing or invalid timeout in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow timeout-minutes must be set with a value less or equal to 60 for every job that is not using a reusable workflow

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual timeout</th>
			<th>Expected</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>Not found</td>
				<td><= 60</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowTimeout)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>


Commit [`ba89f61`](https://github.com/pipedrive/client-nodejs/commit/ba89f61ca2d8b4a63e9b82c065fa82e8da3fbdeb/)  Job [`285377`](https://jenkins.pipedrive.tools/job/neodora/285377/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Missing Snyk Branch Protection for repository</strong></summary>
<br/>

**Message:** Branch protection must be configured on every GitHub repository. Snyk checks must be in the list of required checks of the branch protection rule

<table>
<thead>
	<tr>
			<th>Snyk checks status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/settings/branches">Required checks are missing: code/snyk</a></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/snykBranchProtection)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/e082670d0891b747b2bb190e4430b1252ae7ff06/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/e082670d0891b747b2bb190e4430b1252ae7ff06/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/e082670d0891b747b2bb190e4430b1252ae7ff06/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Missing or invalid timeout in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow timeout-minutes must be set with a value less or equal to 60 for every job that is not using a reusable workflow

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual timeout</th>
			<th>Expected</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/e082670d0891b747b2bb190e4430b1252ae7ff06/.github/workflows/on-pd-bot-pr-opened.yml">on-pd-bot-pr-opened.yml</a></td>
				<td><code>on_pr_opened</code></td>
				<td>Not found</td>
				<td><= 60</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowTimeout)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/client-nodejs/tree/e082670d0891b747b2bb190e4430b1252ae7ff06/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>test-runtime</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>


Commit [`e082670`](https://github.com/pipedrive/client-nodejs/commit/e082670d0891b747b2bb190e4430b1252ae7ff06/)  Job [`285616`](https://jenkins.pipedrive.tools/job/neodora/285616/)

**Pull request merged**
